import fs from "node:fs/promises";
import path from "node:path";

type DocumentStatus = "draft" | "published" | "archived";
type DocumentVisibility = "public" | "hidden" | "secret" | "dm-only";

const GENERATED_MARKER = "AUTO-GENERATED DOCUMENT ROUTE";
const DEFAULT_INPUT = "src/data/documents.json";
const DEFAULT_OUT = "src/pages/documents";

const DOCUMENT_TYPES = new Set([
  "book",
  "lore",
  "rumor",
  "guild-announcement",
  "letter",
  "note",
  "newspaper",
  "diary",
  "report",
  "decree",
  "testimony",
  "contract",
  "prophecy",
  "handout",
  "other",
]);

type RawDocument = {
  id?: unknown;
  title?: unknown;
  type?: unknown;
  status?: unknown;
  visibility?: unknown;
  slug?: unknown;
};

type DocumentRoute = {
  id: string;
  slug: string;
};

type CliOptions = {
  input: string;
  out: string;
  clean: boolean;
  includePrivate: boolean;
  dryRun: boolean;
};

function parseArgs(argv: string[]): CliOptions {
  const options: CliOptions = {
    input: DEFAULT_INPUT,
    out: DEFAULT_OUT,
    clean: false,
    includePrivate: false,
    dryRun: false,
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    const next = argv[index + 1];

    if (arg === "--input" && next) {
      options.input = next;
      index += 1;
      continue;
    }

    if (arg === "--out" && next) {
      options.out = next;
      index += 1;
      continue;
    }

    if (arg === "--clean") {
      options.clean = true;
      continue;
    }

    if (arg === "--include-private") {
      options.includePrivate = true;
      continue;
    }

    if (arg === "--dry-run") {
      options.dryRun = true;
      continue;
    }

    throw new Error(`Unknown or incomplete argument: ${arg}`);
  }

  return options;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function normalizeDocuments(value: unknown): RawDocument[] {
  if (Array.isArray(value)) {
    return value as RawDocument[];
  }

  if (isRecord(value)) {
    return Object.values(value) as RawDocument[];
  }

  throw new Error("documents.json must be either an array or an object record.");
}

function getDocumentLabel(document: RawDocument, index: number): string {
  return typeof document.id === "string" && document.id.trim()
    ? document.id
    : `at index ${index}`;
}

function validateDocument(value: RawDocument, index: number): asserts value is RawDocument {
  if (!isRecord(value)) {
    throw new Error(`Document at index ${index} must be an object.`);
  }

  const document = value;
  const label = getDocumentLabel(document, index);

  if (typeof document.id !== "string" || !document.id.trim()) {
    throw new Error(`Document ${label} has no id.`);
  }

  if (typeof document.title !== "string" || !document.title.trim()) {
    throw new Error(`Document "${document.id}" has no title.`);
  }

  if (typeof document.type !== "string" || !DOCUMENT_TYPES.has(document.type)) {
    throw new Error(`Document "${document.id}" has invalid type "${String(document.type)}".`);
  }
}

function isPublishedPublic(document: RawDocument): boolean {
  return document.status === "published" && document.visibility === "public";
}

function shouldGenerateDocument(document: RawDocument, includePrivate: boolean): boolean {
  if (isPublishedPublic(document)) return true;

  return includePrivate && document.status === "published";
}

function slugify(value: string): string {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function getRouteSlug(document: RawDocument): string {
  const rawSlug =
    typeof document.slug === "string" && document.slug.trim()
      ? document.slug
      : String(document.id);
  const slug = slugify(rawSlug);

  if (!slug) {
    throw new Error(`Document "${String(document.id)}" generated an empty route slug.`);
  }

  return slug;
}

function buildRoutes(documents: RawDocument[], includePrivate: boolean): DocumentRoute[] {
  const routes: DocumentRoute[] = [];
  const routeBySlug = new Map<string, string>();

  documents.forEach((document, index) => {
    validateDocument(document, index);

    if (!shouldGenerateDocument(document, includePrivate)) return;

    const id = document.id as string;
    const slug = getRouteSlug(document);
    const existingDocumentId = routeBySlug.get(slug);

    if (existingDocumentId) {
      throw new Error(
        `Duplicate document route slug "${slug}" generated by "${existingDocumentId}" and "${id}".`,
      );
    }

    routeBySlug.set(slug, id);
    routes.push({ id, slug });
  });

  return routes.sort((a, b) => a.slug.localeCompare(b.slug));
}

function renderRoute(documentId: string): string {
  return `// ${GENERATED_MARKER}
// Do not edit manually. Run npm run gen:documents instead.

import React from "react";
import DocumentReaderPage from "@site/src/components/documents/DocumentReaderPage";

export default function GeneratedDocumentPage() {
  return <DocumentReaderPage documentId=${JSON.stringify(documentId)} />;
}
`;
}

async function pathExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function cleanGeneratedRoutes(outputDir: string, dryRun: boolean): Promise<number> {
  if (!(await pathExists(outputDir))) return 0;

  const entries = await fs.readdir(outputDir, { withFileTypes: true });
  let removedCount = 0;

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith(".tsx")) continue;

    const filePath = path.join(outputDir, entry.name);
    const contents = await fs.readFile(filePath, "utf8");

    if (!contents.includes(GENERATED_MARKER)) continue;

    removedCount += 1;

    if (dryRun) {
      console.log(`[dry-run] Would remove ${filePath}`);
      continue;
    }

    await fs.rm(filePath);
  }

  return removedCount;
}

async function writeRoutes(routes: DocumentRoute[], outputDir: string, dryRun: boolean) {
  if (!dryRun) {
    await fs.mkdir(outputDir, { recursive: true });
  }

  for (const route of routes) {
    const outputPath = path.join(outputDir, `${route.slug}.tsx`);
    const contents = renderRoute(route.id);

    if (dryRun) {
      console.log(`[dry-run] Would write ${outputPath}`);
      continue;
    }

    await fs.writeFile(outputPath, contents);
  }
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  const rawJson = await fs.readFile(options.input, "utf8");
  const documents = normalizeDocuments(JSON.parse(rawJson));
  const routes = buildRoutes(documents, options.includePrivate);

  const cleanedCount = options.clean
    ? await cleanGeneratedRoutes(options.out, options.dryRun)
    : 0;

  await writeRoutes(routes, options.out, options.dryRun);

  const prefix = options.dryRun ? "[dry-run] " : "";
  console.log(
    `${prefix}Generated ${routes.length} document route(s) in ${options.out}. Cleaned ${cleanedCount}.`,
  );
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
